#!/usr/bin/env python3
"""Export the Hearer label map to a TypeScript file the runtime can import.

The runtime never parses YAML at boot; it imports the generated map.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _lib import REPO_ROOT, info, load_labels  # type: ignore


HEADER = """// AUTO-GENERATED by ml/scripts/export_label_map.py — do not edit by hand.
// Regenerate with: python ml/scripts/export_label_map.py
//
// This file mirrors ml/hearer_labels.yaml so the runtime can render
// labels and routing thresholds without parsing YAML.

export interface HearerLabelEntry {
  id: string;
  displayName: string;
  category: string;
  defaultPriority: "low" | "medium" | "high" | "urgent";
  actionType: "physical" | "digital" | "awareness";
  minConfidenceForInterrupt: number;
  cueTemplates: Record<string, string>;
  sourceMappings: Record<string, string[]>;
}
"""


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "src" / "audio" / "hearerLabelMap.generated.ts",
    )
    return p.parse_args()


def ts_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def main() -> int:
    args = parse_args()
    data = load_labels()
    labels = data.get("labels", {})
    args.output.parent.mkdir(parents=True, exist_ok=True)

    parts = [HEADER]
    parts.append("\nexport const HEARER_LABEL_MAP: Record<string, HearerLabelEntry> = {\n")
    for label_id, spec in labels.items():
        spec = spec or {}
        cue_templates = spec.get("cueTemplates") or {}
        source_mappings = spec.get("sourceMappings") or {}
        parts.append(f"  {ts_string(label_id)}: {{\n")
        parts.append(f"    id: {ts_string(label_id)},\n")
        parts.append(f"    displayName: {ts_string(spec.get('displayName', label_id))},\n")
        parts.append(f"    category: {ts_string(spec.get('category', 'unknown'))},\n")
        parts.append(
            f"    defaultPriority: {ts_string(spec.get('defaultPriority', 'low'))} as HearerLabelEntry[\"defaultPriority\"],\n"
        )
        parts.append(
            f"    actionType: {ts_string(spec.get('actionType', 'awareness'))} as HearerLabelEntry[\"actionType\"],\n"
        )
        parts.append(
            f"    minConfidenceForInterrupt: {float(spec.get('minConfidenceForInterrupt', 1.01))},\n"
        )
        parts.append("    cueTemplates: {")
        for k, v in cue_templates.items():
            parts.append(f" {ts_string(k)}: {ts_string(v)},")
        parts.append(" },\n")
        parts.append("    sourceMappings: {")
        for src, items in source_mappings.items():
            items_ts = ", ".join(ts_string(it) for it in items)
            parts.append(f" {ts_string(src)}: [{items_ts}],")
        parts.append(" },\n")
        parts.append("  },\n")
    parts.append("};\n")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("".join(parts))
    info(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
